### ISSUE TITLE
Contribution and docs section on README.md

### ISSUE THREAD

**Issue by LucianaMarques** [mlbench/mlbench-core#17]
Hello there,

I came across this project on the web and found it really interesting. Since I'm willing to contribute to it, I looked for informations on contributions and only found it on https://mlbench.readthedocs.io/

I'd like to suggest on this issue to add a new "Contributing" section on README.md, that can contain general information to whoever willing to contribute and a link to the contributing page on the documentation. 

I can submit a pull request later if such changes are approved :)

**Comment by Panaetius** [comment]
Hey there.

Thank you for your suggestion :)

The MLBench project is split across 5 github repositories and is organized in such a way that the main docs of the project are in the 'mlbench-docs' repository, with docs from the other repos getting automatically included in the main docs when they are deployed to the read-the-docs page (the menu-points under 'Components' in the docs are the docs of the various repos). There's also the blog at https://mlbench.github.io/ 

To prevent duplicating information, I think it makes sense to only have a single contributing section for the whole project in the main docs instead of having information split across the various repos. I.e. all the information for contributing to the MLBench project should be in one location.

That said, it would certainly make sense to update the individual readmes of the repos to be more informative, like adding a link to the contributing page and explaining that the codebase is split across several repos. This would allow newcomers to more quickly get an overview or everything.

And I just saw, the docs only refer to the mailing list right now, which is largely inactive, but there's no information about the developer Slack channel. So it'd be a good idea to add that information as well, since it's the best place to get in contact with all the devs ( https://join.slack.com/t/mlbench/shared_invite/enQtNTMzMjkwNDA4MTAyLWM2NTQ4OGNjMjFmZDdhMGQ2YzZkYmUyNzMxN2QxZjc2MmQyNjNiNjM3YWFlYzAwZjQ0Yzc0MTc3YWY5Zjg1ZjU ).

If you are willing to change this, you are more than welcome to submit a pull request :)

I also noticed that the contributing section itself is a bit out of date (The whole 'Getting Started' Section is wrong for the current state of the project. it only somewhat applies to 'mlbench-core' and has no info about the other repos and how to use those) and the "Tips" and "Deploying" sections are not relevant anymore, either. I've created a new ticket to update the contributing page to the current state of the project at https://github.com/mlbench/mlbench-docs/issues/4

**Comment by LucianaMarques** [comment]
Hi there, I just wanted to apologize for not showing up with a PR lately, I've never used Google cloud before and am still getting used to it. I had little time on the past days but will come up here as soon as I can.

**Comment by Panaetius** [comment]
No worries. Feel free to ask questions on discord if you're having problems getting up and running. And feedback is always welcome, in case there's something we might add to make things more beginner friendly :)

**Comment by LucianaMarques** [comment]
> No worries. Feel free to ask questions on discord if you're having problems getting up and running. And feedback is always welcome, in case there's something we might add to make things more beginner friendly :)

Thanks! I started on February a new internship and I was very busy in week days! But I'm trying to come back whenever I can. 

Something that occurred to me was the following:

On the doc's prerequisites, you mention Google Clouds (Clusters and Kubernets). There is plenty of information on Google's website, and lots of redirecting to new tabs and it can be a little overwhelming to beginners on the matter. Do you think it's ok to provide better guidance in this matter on the docs itself, and not just redirecting to google' website (thinking about beginners)? I always like to provide the best on instructions and assume little as possible from the user (except when a certain expertise is already expected), but I understand that some developers think differently.

**Comment by LucianaMarques** [comment]
Just to be more specific, I think we could create some kind of instructions like:

1. Install Google Cloud SDK
2. Create a project
3. Enable Kubernetes API
4. Create a Clubes
... etc

**Comment by Panaetius** [comment]
I agree that better documentation would be helpful. But as there's a lot of steps to set up a cluster and there's several ways to run the code (Google Cloud, locally in a kubeadm-dind-cluster, in the future on AWS, possibly others), it'd make for some pretty lengthy documentation.

Hopefully with the new setup scripts, a lot of this will be mitigated. So for now I'd hold off on adding too much documentation, waiting until that's finished. Ideally, a beginner will just have to call the correct script with his credentials/settings, and then access the Dashboard URL to run experiments from there.
