### ISSUE TITLE
Add some integration tests

### ISSUE THREAD

**Issue by cgrigis** [mlbench/mlbench-core#64]
I could not find integration tests.
Those are not always easy to write :-) , but do you think that some tests related to Kubernetes could be automated in Travis using perhaps [this approach](https://blog.travis-ci.com/2017-10-26-running-kubernetes-on-travis-ci-with-minikube)?

**Comment by Panaetius** [comment]
Minikube is always tricky since mlbench by design wants pods to run on different nodes so they don't influences each others results, and minikube is limited to 1 node (to the best of my knowldge). But for something like integration tests, it'd could still work.

I'm all for having integration tests, great suggestion!

**Comment by ehoelzl** [comment]
Integration tests have been added to the dashboard (deploying and creating runs) see https://github.com/mlbench/mlbench-dashboard/commit/c6aeb3a00f7bc3fa527f56ab1c11d39084153c0d
