### ISSUE TITLE
Fix random seeds

### ISSUE THREAD

**Issue by giorgiosav** [mlbench/mlbench-core#79]
Different runs on the same benchmark produce different results due to random seeds. We should check what MLPerf does to avoid this and maybe fix the random seeds.

**Comment by ehoelzl** [comment]
@martinjaggi @IamTao How would you like to approach this issue ?

Currently, the seed is set using `random.seed(seed)` and `torch.manual_seed(seed)`.  Not sure how those behave though.

To have reproducible runs, we need to fix the initialization of weights and batches need to be the same for all runs. 

I can work on that once the TransformerModel is done.

**Comment by IamTao** [comment]
maybe we should also set the seed for `torch.cuda.manual_seed`? but due to the async property of GPU, maybe it is too hard to 100% control the randomness?

For most of my projects, I will also configure `torch.backends.cudnn.enabled`, `torch.backends.cudnn.benchmark`, and `torch.backends.cudnn.deterministic`.

Have you ever tested reproducibility on these combinations?

**Comment by ehoelzl** [comment]
According to [Pytorch](https://pytorch.org/docs/stable/notes/randomness.html) we should set `torch.backends.cudnn.benchmark = False`.

**Comment by Panaetius** [comment]
This is done, right?
